import { useEffect } from "react";
import { StatsCards } from "@/components/StatsCards";
import { AtlasMap } from "@/components/map/AtlasMap";
import { ClaimAnalyzer } from "@/components/ai/ClaimAnalyzer";

export default function Index() {
  useEffect(() => {
    try {
      const rawHash = window.location.hash;
      if (!rawHash) return;
      // remove query params if present (e.g. #about?reload=123)
      const clean = rawHash.split("?")[0];
      const id = clean.startsWith("#") ? clean.slice(1) : clean;
      if (!id) return;
      const el = document.getElementById(id);
      if (el) el.scrollIntoView({ behavior: "smooth" });
    } catch (err) {
      console.warn("Failed to scroll to hash:", err);
    }
  }, []);

  return (
    <main className="flex-1">
      {/* Hero */}
      <section className="container py-16 md:py-24">
        <div className="grid md:grid-cols-2 gap-10 items-center">
          <div>
            <div className="inline-flex items-center gap-2 rounded-full border px-3 py-1 text-xs bg-accent">
              <span className="h-2 w-2 rounded-full bg-primary" />
                AI-powered FRA Atlas & WebGIS DSS
            </div>
            <h1 className="mt-4 text-4xl md:text-5xl font-extrabold tracking-tight">
              Forest Rights Act Atlas for Government Decision Support
            </h1>
            <p className="mt-4 text-muted-foreground text-lg">
              An end-to-end MVP showcasing geospatial analytics and mock AI/ML pipelines
              for verification, monitoring, and planning under the FRA.
            </p>
            <div className="mt-6 flex flex-wrap gap-3">
              <a href="#atlas" className="inline-flex items-center justify-center rounded-md bg-primary hover:bg-emerald-500 text-white px-5 py-3 font-medium shadow-sm">Open Atlas</a>
              <a href="#analysis" className="inline-flex items-center justify-center rounded-md border px-5 py-3 font-medium">Run AI Analysis</a>
            </div>
            <div className="mt-8">
              <StatsCards />
            </div>
          </div>
          <div className="relative">
            <div className="absolute inset-0 bg-gradient-to-br from-emerald-200/40 to-green-200/40 rounded-3xl blur-2xl" />
            <div className="relative rounded-2xl border bg-card p-4 shadow-lg">
              <AtlasMap />
            </div>
          </div>
        </div>
      </section>

      {/* Atlas */}
      <section id="atlas" className="container py-12 md:py-16">
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-2xl font-bold">Interactive Atlas</h2>
          <p className="text-sm text-muted-foreground">Toggle forest boundaries and claims. Uses OSM base map.</p>
        </div>
        <AtlasMap />
      </section>

      {/* Analysis */}
      <section id="analysis" className="container py-12 md:py-16">
        <h2 className="text-2xl font-bold">AI Claim Analysis (Mock)</h2>
        <p className="mt-2 text-muted-foreground max-w-3xl">
          Simulates risk scoring, anomaly detection, and recommended actions for a selected claim.
          All results are generated by deterministic mock functions—no models required.
        </p>
        <div className="mt-6">
          <ClaimAnalyzer />
        </div>
      </section>

      {/* About */}
      <section id="about" className="container py-12 md:py-16">
        <h2 className="text-2xl font-bold">About This MVP</h2>
        <div className="mt-3 grid md:grid-cols-3 gap-4 text-sm text-muted-foreground">
          <div className="rounded-xl border p-4">
            <div className="font-semibold text-foreground">Modular Architecture</div>
            <p className="mt-1">Clear separation across client, server, and shared contracts. Replace mock AI with real services when ready.</p>
          </div>
          <div className="rounded-xl border p-4">
            <div className="font-semibold text-foreground">WebGIS-first</div>
            <p className="mt-1">React Leaflet map, OSM tiles, and GeoJSON overlays for forest boundaries and sample claims.</p>
          </div>
          <div className="rounded-xl border p-4">
            <div className="font-semibold text-foreground">Deterministic Mock AI</div>
            <p className="mt-1">Server endpoints return stable, realistic outputs enabling demos without ML dependencies.</p>
          </div>
        </div>
      </section>
    </main>
  );
}
